### ISSUE TITLE
"+" button is not aligned after new layer is added

### ISSUE THREAD

**Issue by MingboPeng** [tt-sus/Uvalue#2]
![image](https://user-images.githubusercontent.com/9031066/27753864-7894ec14-5db5-11e7-9cfa-195522b6ac1b.png)

**Comment by akshar07** [comment]
done

**Comment by MingboPeng** [comment]
The "edit" icon is still not aligned with graphic.
![image](https://user-images.githubusercontent.com/9031066/27972797-9cb2a864-6325-11e7-9ee9-3ad5862868e9.png)
